### PR TITLE
Make migration runner classes public

### PR DESCRIPTION
**Pull request by alvarosanchez**
So that it can be replaced

### CODE REVIEW

**Comment by graemerocher** [comment]
not sure this is enough, we would also need to think about what methods should be overridable

**Comment by alvarosanchez** [comment]
Right, I quickly edited the files via GitHub, but it's true that there are some private methods. Will take a more in-depth look.

**Comment by dstepanov** [comment]
Well you can create a custom interface and do `@Requires(missingBeans = LiquibaseMigrationRunner.class) class DefaultLiquibaseMigrationRunner implemented ILiquibaseMigrationRunner` any aditional requires will be evaluated to the final decision.

**Comment by alvarosanchez** [comment]
Closing this in favour of a proper solution for the underlying problem that another user will contribute in a PR

**Pull request closed without merging**
