### PR TITLE
Adding all dbchangelog xsds to the resource-config.json

### PR DESCRIPTION
**Pull request by DmitryKubahov**
Currently, there is only 1 dbchangelog-3.1.xsd inside resource-config.json which will be the root cause of the issue:
`Caused by: liquibase.parser.core.xml.XSDLookUpException: Unable to resolve xml entity http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd. liquibase.secureParsing is set to 'true' which does not allow remote lookups. Check for spelling or capitalization errors and missing extensions such as liquibase-commercial in your XSD definition. Or, set it to 'false' to allow remote lookups of xsd files.`
for the native image. 
To avoid this: resource-config.json should contain all xsd from the liquibase.jar file include the dbchangelog-latest.xsd too.

Related issue: https://github.com/micronaut-projects/micronaut-liquibase/issues/299

### CODE REVIEW

**Review by alvarosanchez — CHANGES_REQUESTED** [review]
@DmitryKubahov thanks for the contribution, and sorry for the delay in getting back to you.

Manually adding all those entries is not future proof, and will add a mainteance burden that can be avoided if we generate those entries automatically. I see 2 options:
- A [GraalVM feature](https://www.graalvm.org/latest/reference-manual/native-image/dynamic-features/Reflection/#configuration-with-features)
- A custom Gradle task.

Which is the JAR that contains those XSDs? Is there a way we can know the list of them without inspecting the JAR?

**Comment by DmitryKubahov** [comment]
@alvarosanchez thank you for the feedback.
These files are placed in the liquibase-core.jar.
image
And yes, you are right that it is not really good to add them one by one and check every time what was changed in the new version of the liquibase. So, I just changed the pattern from the resource-config.json to the regexp to get them all.
About your suggestions - will it be overhead for this kind of problem? Maybe just using proper regexp will be enough?

**Comment by DmitryKubahov** [comment]
Yes, it works, and if I am using XSD which existed in the liquibase-core.jar file - no issue.

**Review by alvarosanchez — APPROVED** [review]

**Comment by alvarosanchez** [comment]
@sdelamo do you know why the build could be failing?

**Comment by sdelamo** [comment]
@alvarosanchez @DmitryKubahov I have moved this PR to a new PR with 5.5.x as base. 5.5.0 will be included in 3.8.0

**Pull request closed without merging**
